// Package cost provides cost reporting functionality for runs-fleet.
package cost

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"log/slog"
	"time"

	"github.com/Shavakan/runs-fleet/pkg/config"
	"github.com/Shavakan/runs-fleet/pkg/db"
	"github.com/Shavakan/runs-fleet/pkg/fleet"
	"github.com/Shavakan/runs-fleet/pkg/logging"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatch"
	cwtypes "github.com/aws/aws-sdk-go-v2/service/cloudwatch/types"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/sns"
)

var costLog = logging.WithComponent(logging.LogTypeCost, "reporter")

// Pricing constants (approximate AWS pricing in USD)
//
// WARNING: COST ESTIMATES ONLY - NOT FOR BILLING OR FINANCIAL DECISIONS
//
// These prices are hard-coded estimates based on us-east-1 on-demand pricing as of 2024.
// Limitations:
//   - Prices become outdated as AWS adjusts pricing
//   - Does not account for regional price variations
//   - Does not include data transfer, EBS, or other ancillary costs
//   - Spot pricing is estimated as a fixed discount, not actual spot prices
//
// For accurate cost tracking, integrate with:
//   - AWS Cost Explorer API: https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/ce-api.html
//   - AWS Pricing API: https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/price-changes.html
//
// The reports generated by this package should be used for trending and relative
// comparison only, not for actual billing or financial planning.

// familyVCPUHourly is the on-demand price per vCPU-hour for each non-burstable
// instance family, ap-northeast-1. Within such a family AWS prices strictly
// linearly in vCPU count (verified against the Pricing API: c7g, c6i and m7i
// each hold a constant $/vCPU across large/xlarge/2xlarge), so one rate per
// family plus the vCPU count from the instance catalog prices every size --
// including sizes never seen before, which a per-type table cannot.
//
// WARNING: ESTIMATE ONLY. These are ap-northeast-1 list prices; other regions
// differ and no discount programme is modelled. Live prices from the Pricing
// API are always preferred; this is what answers when that call fails.
var familyVCPUHourly = map[string]float64{
	"c7g": 0.0428,
	"c8g": 0.0525,
	"m7g": 0.0490,
	"m8g": 0.0540,
	"r8g": 0.0613,
	"r7g": 0.0803,
	"c6i": 0.0535,
	"c7i": 0.0536,
	"m6i": 0.0610,
	"m7i": 0.0630,
	"r6i": 0.0800,
	"r7i": 0.0840,
}

// burstablePricing prices the t-family per type. Burstable sizes cannot be
// derived from vCPU count: t4g.micro through t4g.large all expose 2 vCPU while
// their prices span 8x, because the tier tracks the memory/credit allowance
// instead. micro and small are listed here although the instance catalog
// deliberately excludes them (too little RAM to host a job) -- a pool can still
// hold one, and it must not price as the flat default.
var burstablePricing = map[string]float64{
	"t3.nano":     0.0068,
	"t3.micro":    0.0136,
	"t3.small":    0.0272,
	"t3.medium":   0.0544,
	"t3.large":    0.1088,
	"t3.xlarge":   0.2176,
	"t3.2xlarge":  0.4352,
	"t4g.nano":    0.0042,
	"t4g.micro":   0.0084,
	"t4g.small":   0.0168,
	"t4g.medium":  0.0336,
	"t4g.large":   0.0672,
	"t4g.xlarge":  0.1344,
	"t4g.2xlarge": 0.2688,
}

// SpotDiscount is the average spot discount compared to on-demand
const SpotDiscount = 0.7 // 70% discount

// DefaultVCPUHourly prices a family absent from familyVCPUHourly. It is near
// the mean of the known families rather than the cheapest: guessing low made
// the old per-type table under-report by up to 14x while looking authoritative.
//
// Exported so a test can assert no selectable family silently lands on it.
const DefaultVCPUHourly = 0.0550

// defaultInstanceHourlyPrice is the rate assumed when neither the family nor
// the vCPU count of an instance type can be resolved.
const defaultInstanceHourlyPrice = 0.0336

// GetInstancePrice returns the estimated on-demand hourly price for an instance
// type, derived from its family's per-vCPU rate and its size.
//
// Unknown families fall back to the mean per-vCPU rate, which still scales with
// size -- so a large instance never prices as a small one. Only a type that is
// neither burstable nor present in the instance catalog takes the flat default.
func GetInstancePrice(instanceType string) float64 {
	if price, ok := burstablePricing[instanceType]; ok {
		return price
	}
	spec, ok := fleet.GetInstanceSpec(instanceType)
	if !ok || spec.CPU <= 0 {
		return defaultInstanceHourlyPrice
	}
	rate, ok := familyVCPUHourly[spec.Family]
	if !ok {
		rate = DefaultVCPUHourly
	}
	return rate * float64(spec.CPU)
}

// CloudWatchAPI defines CloudWatch operations for cost reporting.
type CloudWatchAPI interface {
	GetMetricData(ctx context.Context, params *cloudwatch.GetMetricDataInput, optFns ...func(*cloudwatch.Options)) (*cloudwatch.GetMetricDataOutput, error)
}

// S3API defines S3 operations for storing reports.
type S3API interface {
	PutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options)) (*s3.PutObjectOutput, error)
}

// SNSAPI defines SNS operations for sending notifications.
type SNSAPI interface {
	Publish(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options)) (*sns.PublishOutput, error)
}

// Breakdown represents cost breakdown by service.
type Breakdown struct {
	Date              string
	TotalCost         float64
	EC2SpotCost       float64
	EC2OnDemandCost   float64
	EC2SpotHours      float64
	EC2OnDemandHours  float64
	SpotSavings       float64
	S3Cost            float64
	FargateCost       float64
	SQSCost           float64
	DynamoDBCost      float64
	CloudWatchCost    float64
	JobsCompleted     int
	SpotInterruptions int

	// SpotInterruptionsAvailable reports whether SpotInterruptions was actually
	// observed. It is false when the CloudWatch metrics backend is not publishing
	// the counter (the default) or the query failed, in which case the count is
	// unknown rather than zero.
	SpotInterruptionsAvailable bool

	// RunnerVcpuMinutes is the total billable vCPU-minutes this workload ran
	// (Σ runner-minutes × vCPU), and RunnerMinuteCost is what that usage costs in
	// the standard hosted-runner unit (per-vCPU-minute) — a relative comparison
	// figure, not a runs-fleet billing figure.
	RunnerVcpuMinutes float64
	RunnerMinuteCost  float64
}

// Reporter generates daily cost reports.
type Reporter struct {
	cwClient      CloudWatchAPI
	s3Client      S3API
	snsClient     SNSAPI
	jobs          JobLister
	priceFetcher  PriceFetcherAPI
	spotPricer    SpotPricer
	config        *config.Config
	snsTopicARN   string
	reportsBucket string
}

// PriceFetcherAPI defines the interface for fetching instance prices.
type PriceFetcherAPI interface {
	GetPrice(ctx context.Context, instanceType string) (float64, error)
}

// JobLister lists completed job records for the EC2 cost computation
// (satisfied by *db.Client).
type JobLister interface {
	ListJobsForAdmin(ctx context.Context, filter db.AdminJobFilter) ([]db.AdminJobEntry, int, error)
}

// NewReporter creates a new cost reporter.
// It initializes a PriceFetcher to attempt dynamic pricing lookups from AWS Pricing API.
func NewReporter(cfg aws.Config, jobs JobLister, spotPricer SpotPricer, appConfig *config.Config, snsTopicARN, reportsBucket string) *Reporter {
	return &Reporter{
		cwClient:      cloudwatch.NewFromConfig(cfg),
		s3Client:      s3.NewFromConfig(cfg),
		snsClient:     sns.NewFromConfig(cfg),
		jobs:          jobs,
		priceFetcher:  NewPriceFetcher(cfg, cfg.Region),
		spotPricer:    spotPricer,
		config:        appConfig,
		snsTopicARN:   snsTopicARN,
		reportsBucket: reportsBucket,
	}
}

// NewReporterWithClients creates a new cost reporter with injected clients for testing.
func NewReporterWithClients(cwClient CloudWatchAPI, s3Client S3API, snsClient SNSAPI, jobs JobLister, priceFetcher PriceFetcherAPI, spotPricer SpotPricer, appConfig *config.Config, snsTopicARN, reportsBucket string) *Reporter {
	return &Reporter{
		cwClient:      cwClient,
		s3Client:      s3Client,
		snsClient:     snsClient,
		jobs:          jobs,
		priceFetcher:  priceFetcher,
		spotPricer:    spotPricer,
		config:        appConfig,
		snsTopicARN:   snsTopicARN,
		reportsBucket: reportsBucket,
	}
}

// GenerateDailyReport generates the daily cost report.
// It attempts to fetch current prices from AWS Pricing API and falls back to
// hard-coded estimates if the API is unavailable.
func (r *Reporter) GenerateDailyReport(ctx context.Context) error {
	costLog.Info(ctx, "generating daily cost report")

	endTime := time.Now().UTC().Truncate(time.Hour)
	startTime := endTime.Add(-24 * time.Hour)

	breakdown, err := r.getCostMetrics(ctx, startTime, endTime)
	if err != nil {
		return fmt.Errorf("failed to get cost metrics: %w", err)
	}

	breakdown.Date = startTime.Format("2006-01-02")

	report := r.generateMarkdownReport(breakdown)

	if r.reportsBucket != "" {
		key := fmt.Sprintf("cost/%s/%s/%s.md",
			startTime.Format("2006"),
			startTime.Format("01"),
			startTime.Format("02"))

		_, err = r.s3Client.PutObject(ctx, &s3.PutObjectInput{
			Bucket:      aws.String(r.reportsBucket),
			Key:         aws.String(key),
			Body:        io.NopCloser(bytes.NewReader([]byte(report))),
			ContentType: aws.String("text/markdown"),
		})
		if err != nil {
			costLog.Warn(ctx, "s3 report upload failed", slog.String("error", err.Error()))
		} else {
			costLog.Info(ctx, "report stored in s3", slog.String("bucket", r.reportsBucket), slog.String("key", key))
		}
	}

	if r.snsTopicARN != "" {
		_, err = r.snsClient.Publish(ctx, &sns.PublishInput{
			TopicArn: aws.String(r.snsTopicARN),
			Subject:  aws.String(fmt.Sprintf("runs-fleet Daily Cost Report - %s", breakdown.Date)),
			Message:  aws.String(report),
		})
		if err != nil {
			costLog.Warn(ctx, "sns notification failed", slog.String("error", err.Error()))
		} else {
			costLog.Info(ctx, "report sent via sns")
		}
	}

	costLog.Info(ctx, "daily cost report generated", slog.Float64("total_cost", breakdown.TotalCost))
	return nil
}

// getCostMetrics builds the cost breakdown for the window. The EC2 section is
// computed from completed DynamoDB job records priced with the shared JobPricer
// (exact per-job instance types, spot flags, and durations); spot interruptions
// and runner-minute cost come from CloudWatch metric-math searches.
//
// A job-lister error fails the whole run (housekeeping retries; a zeroed-core
// report is worse than none). CloudWatch errors (interruptions, runner minutes)
// are informational and only degrade those numbers to zero.
func (r *Reporter) getCostMetrics(ctx context.Context, startTime, endTime time.Time) (*Breakdown, error) {
	breakdown := &Breakdown{}

	if err := r.accumulateEC2Costs(ctx, breakdown, startTime, endTime); err != nil {
		return nil, err
	}

	breakdown.SpotInterruptions, breakdown.SpotInterruptionsAvailable = r.spotInterruptionCount(ctx, startTime, endTime)

	// Supporting-service estimates scale off the completed-job count.
	jobs := float64(breakdown.JobsCompleted)

	// Fargate: ~$1.20/day for 1 vCPU, 2GB
	breakdown.FargateCost = 1.20

	// SQS: ~$0.40 per million requests
	estimatedSQSRequests := (jobs * 10) + 1000 // Instance creates + polling
	breakdown.SQSCost = (estimatedSQSRequests / 1000000) * 0.40

	// DynamoDB: PAY_PER_REQUEST, ~$1.25 per million writes, $0.25 per million reads
	estimatedWrites := jobs * 3 // Create, update, complete
	estimatedReads := jobs * 5  // Queue lookups, status checks
	breakdown.DynamoDBCost = (estimatedWrites/1000000)*1.25 + (estimatedReads/1000000)*0.25

	// CloudWatch: Logs ~$0.50/GB, metrics minimal
	estimatedLogGB := jobs * 0.001 // ~1MB per job
	breakdown.CloudWatchCost = estimatedLogGB * 0.50

	// S3: Storage and requests (minimal for cache)
	breakdown.S3Cost = 0.05 // Estimate

	breakdown.TotalCost = breakdown.EC2SpotCost + breakdown.EC2OnDemandCost +
		breakdown.FargateCost + breakdown.SQSCost + breakdown.DynamoDBCost +
		breakdown.CloudWatchCost + breakdown.S3Cost

	// Best-effort: a runner-minute query failure is logged, not returned, so it
	// can't sink the whole cost report.
	vcpuMinutes, runnerCost, err := r.runnerMinuteCost(ctx, startTime, endTime)
	if err != nil {
		costLog.Warn(ctx, "runner-minute cost unavailable", slog.String("error", err.Error()))
	} else {
		breakdown.RunnerVcpuMinutes = vcpuMinutes
		breakdown.RunnerMinuteCost = runnerCost
	}

	return breakdown, nil
}

// accumulateEC2Costs prices every job that finished in the window and fills the
// EC2 fields of the breakdown. "Finished" is keyed on completed_at rather than a
// status value: the stored status is GitHub's raw conclusion
// (success/failure/interrupted/...), all of which burned billable EC2 time,
// while unfinished rows have no duration and would be priced with the pricer's
// 0.5h fallback. A nil lister degrades to zeros (test-path safety); a lister
// error is returned so the run fails.
func (r *Reporter) accumulateEC2Costs(ctx context.Context, breakdown *Breakdown, startTime, endTime time.Time) error {
	if r.jobs == nil {
		costLog.Warn(ctx, "job lister unavailable, EC2 costs computed from zero jobs")
		return nil
	}

	jobs, _, err := r.jobs.ListJobsForAdmin(ctx, db.AdminJobFilter{
		CompletedOnly: true,
		Since:         startTime,
		Until:         endTime,
	})
	if err != nil {
		return fmt.Errorf("failed to list completed jobs: %w", err)
	}

	pricer := NewJobPricer(r.priceFetcher, r.spotPricer)
	for _, job := range jobs {
		p := pricer.Price(ctx, job)
		breakdown.EC2SpotCost += p.Spot
		breakdown.EC2OnDemandCost += p.OnDemand
		breakdown.SpotSavings += p.Savings
		if job.Spot {
			breakdown.EC2SpotHours += p.Hours
		} else {
			breakdown.EC2OnDemandHours += p.Hours
		}
	}
	breakdown.JobsCompleted = len(jobs)
	return nil
}

// spotInterruptionCount sums the SpotInterruptions metric across the Family
// dimension for the window, reporting whether the count could be observed at all.
//
// The metric exists only when the CloudWatch metrics backend is publishing it, and
// that backend ships disabled. An absent series is therefore the common case, not
// an error — but it is also not zero interruptions, so it must not be rendered as
// one. A query failure is likewise unavailable rather than zero.
func (r *Reporter) spotInterruptionCount(ctx context.Context, startTime, endTime time.Time) (int, bool) {
	output, err := r.cwClient.GetMetricData(ctx, &cloudwatch.GetMetricDataInput{
		StartTime:         aws.Time(startTime),
		EndTime:           aws.Time(endTime),
		MetricDataQueries: spotInterruptionQueries(),
	})
	if err != nil {
		costLog.Warn(ctx, "spot interruption count unavailable", slog.String("error", err.Error()))
		return 0, false
	}

	var sum float64
	var observed bool
	for _, result := range output.MetricDataResults {
		if result.Id == nil || *result.Id != spotInterruptionQueryID {
			continue
		}
		for _, v := range result.Values {
			sum += v
			observed = true
		}
	}
	return int(sum), observed
}

const spotInterruptionQueryID = "spot_interruptions"

// spotInterruptionQueries builds the metric-math query that sums the
// SpotInterruptions counter across the Family dimension (the real emissions
// carry a Family dimension, so a plain undimensioned lookup matches nothing).
func spotInterruptionQueries() []cwtypes.MetricDataQuery {
	return []cwtypes.MetricDataQuery{
		{
			Id:         aws.String(spotInterruptionQueryID),
			Expression: aws.String(`SUM(SEARCH('{RunsFleet,Family} MetricName="SpotInterruptions"', 'Sum', 3600))`),
			ReturnData: aws.Bool(true),
		},
	}
}

// generateMarkdownReport generates a markdown report from the cost breakdown.
func (r *Reporter) generateMarkdownReport(b *Breakdown) string {
	var buf bytes.Buffer

	buf.WriteString("# runs-fleet Daily Cost Report\n\n")
	buf.WriteString(fmt.Sprintf("**Date:** %s\n\n", b.Date))
	buf.WriteString(fmt.Sprintf("**24-Hour Total:** $%.2f\n\n", b.TotalCost))

	buf.WriteString("## EC2 Compute\n\n")
	buf.WriteString(fmt.Sprintf("- Spot instances: $%.2f (%.1f instance-hours)\n", b.EC2SpotCost, b.EC2SpotHours))
	buf.WriteString(fmt.Sprintf("- On-demand instances: $%.2f (%.1f instance-hours)\n", b.EC2OnDemandCost, b.EC2OnDemandHours))
	buf.WriteString(fmt.Sprintf("- **Spot savings:** $%.2f (%.0f%% discount)\n\n", b.SpotSavings, SpotDiscount*100))

	buf.WriteString("## Supporting Services\n\n")
	buf.WriteString(fmt.Sprintf("- Fargate orchestrator: $%.2f\n", b.FargateCost))
	buf.WriteString(fmt.Sprintf("- SQS: $%.2f\n", b.SQSCost))
	buf.WriteString(fmt.Sprintf("- DynamoDB: $%.2f\n", b.DynamoDBCost))
	buf.WriteString(fmt.Sprintf("- CloudWatch: $%.2f\n", b.CloudWatchCost))
	buf.WriteString(fmt.Sprintf("- S3: $%.2f\n\n", b.S3Cost))

	buf.WriteString("## Job Statistics\n\n")
	buf.WriteString(fmt.Sprintf("- Jobs completed: %d\n", b.JobsCompleted))
	if b.SpotInterruptionsAvailable {
		buf.WriteString(fmt.Sprintf("- Spot interruptions: %d\n", b.SpotInterruptions))
	} else {
		buf.WriteString("- Spot interruptions: unavailable (CloudWatch metrics disabled)\n")
	}
	if b.JobsCompleted > 0 {
		costPerJob := b.TotalCost / float64(b.JobsCompleted)
		buf.WriteString(fmt.Sprintf("- Cost per job: $%.4f\n", costPerJob))
	}

	if b.RunnerMinuteCost > 0 {
		buf.WriteString("\n## Runner-Minute Cost (standard per-vCPU-minute pricing)\n\n")
		buf.WriteString(fmt.Sprintf("- Billable runner usage: %.0f vCPU-minutes\n", b.RunnerVcpuMinutes))
		buf.WriteString(fmt.Sprintf("- Standard runner-minute cost: $%.2f\n", b.RunnerMinuteCost))
		ec2Cost := b.EC2SpotCost + b.EC2OnDemandCost
		if ec2Cost > 0 {
			buf.WriteString(fmt.Sprintf("- runs-fleet EC2 compute: $%.2f (%.1fx lower)\n", ec2Cost, b.RunnerMinuteCost/ec2Cost))
		}
	}

	buf.WriteString("\n---\n")
	buf.WriteString("⚠️ **DISCLAIMER:** These costs are *estimates* based on hard-coded pricing data.\n")
	buf.WriteString("Actual AWS costs may vary. Use AWS Cost Explorer for accurate billing data.\n\n")
	buf.WriteString("*Report generated by runs-fleet*\n")

	return buf.String()
}
