// Package cost provides cost reporting functionality for runs-fleet.
package cost

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"log/slog"
	"time"

	"github.com/Shavakan/runs-fleet/pkg/config"
	"github.com/Shavakan/runs-fleet/pkg/db"
	"github.com/Shavakan/runs-fleet/pkg/logging"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatch"
	cwtypes "github.com/aws/aws-sdk-go-v2/service/cloudwatch/types"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/sns"
)

var costLog = logging.WithComponent(logging.LogTypeCost, "reporter")

// Pricing constants (approximate AWS pricing in USD)
//
// WARNING: COST ESTIMATES ONLY - NOT FOR BILLING OR FINANCIAL DECISIONS
//
// These prices are hard-coded estimates based on us-east-1 on-demand pricing as of 2024.
// Limitations:
//   - Prices become outdated as AWS adjusts pricing
//   - Does not account for regional price variations
//   - Does not include data transfer, EBS, or other ancillary costs
//   - Spot pricing is estimated as a fixed discount, not actual spot prices
//
// For accurate cost tracking, integrate with:
//   - AWS Cost Explorer API: https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/ce-api.html
//   - AWS Pricing API: https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/price-changes.html
//
// The reports generated by this package should be used for trending and relative
// comparison only, not for actual billing or financial planning.
var instancePricing = map[string]float64{
	// On-demand prices (per hour, us-east-1, approximate)
	"t4g.micro":   0.0084,
	"t4g.small":   0.0168,
	"t4g.medium":  0.0336,
	"t4g.large":   0.0672,
	"t4g.xlarge":  0.1344,
	"t4g.2xlarge": 0.2688,
	"c7g.medium":  0.0361,
	"c7g.large":   0.0725,
	"c7g.xlarge":  0.1450,
	"c7g.2xlarge": 0.2900,
	"m7g.medium":  0.0408,
	"m7g.large":   0.0816,
	"m7g.xlarge":  0.1632,
	"m7g.2xlarge": 0.3264,
}

// SpotDiscount is the average spot discount compared to on-demand
const SpotDiscount = 0.7 // 70% discount

// defaultInstanceHourlyPrice is the on-demand hourly rate assumed for an instance
// type absent from instancePricing (and when the live Pricing API is unavailable).
// It mirrors the t4g.medium rate — our smallest common default tier.
const defaultInstanceHourlyPrice = 0.0336

// GetInstancePrice returns the hard-coded on-demand hourly price for an instance type.
// Returns the t4g.medium price as default for unknown types.
func GetInstancePrice(instanceType string) float64 {
	if price, ok := instancePricing[instanceType]; ok {
		return price
	}
	return defaultInstanceHourlyPrice
}

// CloudWatchAPI defines CloudWatch operations for cost reporting.
type CloudWatchAPI interface {
	GetMetricData(ctx context.Context, params *cloudwatch.GetMetricDataInput, optFns ...func(*cloudwatch.Options)) (*cloudwatch.GetMetricDataOutput, error)
}

// S3API defines S3 operations for storing reports.
type S3API interface {
	PutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.Options)) (*s3.PutObjectOutput, error)
}

// SNSAPI defines SNS operations for sending notifications.
type SNSAPI interface {
	Publish(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options)) (*sns.PublishOutput, error)
}

// Breakdown represents cost breakdown by service.
type Breakdown struct {
	Date              string
	TotalCost         float64
	EC2SpotCost       float64
	EC2OnDemandCost   float64
	EC2SpotHours      float64
	EC2OnDemandHours  float64
	SpotSavings       float64
	S3Cost            float64
	FargateCost       float64
	SQSCost           float64
	DynamoDBCost      float64
	CloudWatchCost    float64
	JobsCompleted     int
	SpotInterruptions int

	// JobsMatched is the pre-cap count of jobs matching the window; when it
	// exceeds JobsCompleted the priced set was truncated at jobWindowLimit and
	// the EC2 figures undercount.
	JobsMatched int

	// RunnerVcpuMinutes is the total billable vCPU-minutes this workload ran
	// (Σ runner-minutes × vCPU), and RunnerMinuteCost is what that usage costs in
	// the standard hosted-runner unit (per-vCPU-minute) — a relative comparison
	// figure, not a runs-fleet billing figure.
	RunnerVcpuMinutes float64
	RunnerMinuteCost  float64
}

// Reporter generates daily cost reports.
type Reporter struct {
	cwClient      CloudWatchAPI
	s3Client      S3API
	snsClient     SNSAPI
	jobs          JobLister
	priceFetcher  PriceFetcherAPI
	spotPricer    SpotPricer
	config        *config.Config
	snsTopicARN   string
	reportsBucket string
}

// PriceFetcherAPI defines the interface for fetching instance prices.
type PriceFetcherAPI interface {
	GetPrice(ctx context.Context, instanceType string) (float64, error)
}

// JobLister lists completed job records for the EC2 cost computation
// (satisfied by *db.Client).
type JobLister interface {
	ListJobsForAdmin(ctx context.Context, filter db.AdminJobFilter) ([]db.AdminJobEntry, int, error)
}

// NewReporter creates a new cost reporter.
// It initializes a PriceFetcher to attempt dynamic pricing lookups from AWS Pricing API.
func NewReporter(cfg aws.Config, jobs JobLister, spotPricer SpotPricer, appConfig *config.Config, snsTopicARN, reportsBucket string) *Reporter {
	return &Reporter{
		cwClient:      cloudwatch.NewFromConfig(cfg),
		s3Client:      s3.NewFromConfig(cfg),
		snsClient:     sns.NewFromConfig(cfg),
		jobs:          jobs,
		priceFetcher:  NewPriceFetcher(cfg, cfg.Region),
		spotPricer:    spotPricer,
		config:        appConfig,
		snsTopicARN:   snsTopicARN,
		reportsBucket: reportsBucket,
	}
}

// NewReporterWithClients creates a new cost reporter with injected clients for testing.
func NewReporterWithClients(cwClient CloudWatchAPI, s3Client S3API, snsClient SNSAPI, jobs JobLister, priceFetcher PriceFetcherAPI, spotPricer SpotPricer, appConfig *config.Config, snsTopicARN, reportsBucket string) *Reporter {
	return &Reporter{
		cwClient:      cwClient,
		s3Client:      s3Client,
		snsClient:     snsClient,
		jobs:          jobs,
		priceFetcher:  priceFetcher,
		spotPricer:    spotPricer,
		config:        appConfig,
		snsTopicARN:   snsTopicARN,
		reportsBucket: reportsBucket,
	}
}

// GenerateDailyReport generates the daily cost report.
// It attempts to fetch current prices from AWS Pricing API and falls back to
// hard-coded estimates if the API is unavailable.
func (r *Reporter) GenerateDailyReport(ctx context.Context) error {
	costLog.Info(ctx, "generating daily cost report")

	endTime := time.Now().UTC().Truncate(time.Hour)
	startTime := endTime.Add(-24 * time.Hour)

	breakdown, err := r.getCostMetrics(ctx, startTime, endTime)
	if err != nil {
		return fmt.Errorf("failed to get cost metrics: %w", err)
	}

	breakdown.Date = startTime.Format("2006-01-02")

	report := r.generateMarkdownReport(breakdown)

	if r.reportsBucket != "" {
		key := fmt.Sprintf("cost/%s/%s/%s.md",
			startTime.Format("2006"),
			startTime.Format("01"),
			startTime.Format("02"))

		_, err = r.s3Client.PutObject(ctx, &s3.PutObjectInput{
			Bucket:      aws.String(r.reportsBucket),
			Key:         aws.String(key),
			Body:        io.NopCloser(bytes.NewReader([]byte(report))),
			ContentType: aws.String("text/markdown"),
		})
		if err != nil {
			costLog.Warn(ctx, "s3 report upload failed", slog.String("error", err.Error()))
		} else {
			costLog.Info(ctx, "report stored in s3", slog.String("bucket", r.reportsBucket), slog.String("key", key))
		}
	}

	if r.snsTopicARN != "" {
		_, err = r.snsClient.Publish(ctx, &sns.PublishInput{
			TopicArn: aws.String(r.snsTopicARN),
			Subject:  aws.String(fmt.Sprintf("runs-fleet Daily Cost Report - %s", breakdown.Date)),
			Message:  aws.String(report),
		})
		if err != nil {
			costLog.Warn(ctx, "sns notification failed", slog.String("error", err.Error()))
		} else {
			costLog.Info(ctx, "report sent via sns")
		}
	}

	costLog.Info(ctx, "daily cost report generated", slog.Float64("total_cost", breakdown.TotalCost))
	return nil
}

// getCostMetrics builds the cost breakdown for the window. The EC2 section is
// computed from completed DynamoDB job records priced with the shared JobPricer
// (exact per-job instance types, spot flags, and durations); spot interruptions
// and runner-minute cost come from CloudWatch metric-math searches.
//
// A job-lister error fails the whole run (housekeeping retries; a zeroed-core
// report is worse than none). CloudWatch errors (interruptions, runner minutes)
// are informational and only degrade those numbers to zero.
func (r *Reporter) getCostMetrics(ctx context.Context, startTime, endTime time.Time) (*Breakdown, error) {
	breakdown := &Breakdown{}

	if err := r.accumulateEC2Costs(ctx, breakdown, startTime, endTime); err != nil {
		return nil, err
	}

	breakdown.SpotInterruptions = r.spotInterruptionCount(ctx, startTime, endTime)

	// Supporting-service estimates scale off the completed-job count.
	jobs := float64(breakdown.JobsCompleted)

	// Fargate: ~$1.20/day for 1 vCPU, 2GB
	breakdown.FargateCost = 1.20

	// SQS: ~$0.40 per million requests
	estimatedSQSRequests := (jobs * 10) + 1000 // Instance creates + polling
	breakdown.SQSCost = (estimatedSQSRequests / 1000000) * 0.40

	// DynamoDB: PAY_PER_REQUEST, ~$1.25 per million writes, $0.25 per million reads
	estimatedWrites := jobs * 3 // Create, update, complete
	estimatedReads := jobs * 5  // Queue lookups, status checks
	breakdown.DynamoDBCost = (estimatedWrites/1000000)*1.25 + (estimatedReads/1000000)*0.25

	// CloudWatch: Logs ~$0.50/GB, metrics minimal
	estimatedLogGB := jobs * 0.001 // ~1MB per job
	breakdown.CloudWatchCost = estimatedLogGB * 0.50

	// S3: Storage and requests (minimal for cache)
	breakdown.S3Cost = 0.05 // Estimate

	breakdown.TotalCost = breakdown.EC2SpotCost + breakdown.EC2OnDemandCost +
		breakdown.FargateCost + breakdown.SQSCost + breakdown.DynamoDBCost +
		breakdown.CloudWatchCost + breakdown.S3Cost

	// Best-effort: a runner-minute query failure is logged, not returned, so it
	// can't sink the whole cost report.
	vcpuMinutes, runnerCost, err := r.runnerMinuteCost(ctx, startTime, endTime)
	if err != nil {
		costLog.Warn(ctx, "runner-minute cost unavailable", slog.String("error", err.Error()))
	} else {
		breakdown.RunnerVcpuMinutes = vcpuMinutes
		breakdown.RunnerMinuteCost = runnerCost
	}

	return breakdown, nil
}

// jobWindowLimit caps how many completed jobs one report prices, matching the
// admin cost endpoints' accepted cap.
const jobWindowLimit = 10000

// accumulateEC2Costs prices the window's completed jobs and fills the EC2 fields
// of the breakdown. A nil lister degrades to zeros (test-path safety); a lister
// error is returned so the run fails.
func (r *Reporter) accumulateEC2Costs(ctx context.Context, breakdown *Breakdown, startTime, endTime time.Time) error {
	if r.jobs == nil {
		costLog.Warn(ctx, "job lister unavailable, EC2 costs computed from zero jobs")
		return nil
	}

	jobs, total, err := r.jobs.ListJobsForAdmin(ctx, db.AdminJobFilter{
		Status: string(db.JobStatusCompleted),
		Since:  startTime,
		Until:  endTime,
		Limit:  jobWindowLimit,
	})
	if err != nil {
		return fmt.Errorf("failed to list completed jobs: %w", err)
	}
	if total > len(jobs) {
		costLog.Warn(ctx, "job window truncated, EC2 costs undercount",
			slog.Int("priced_jobs", len(jobs)), slog.Int("matched_jobs", total))
	}

	pricer := NewJobPricer(r.priceFetcher, r.spotPricer)
	for _, job := range jobs {
		p := pricer.Price(ctx, job)
		breakdown.EC2SpotCost += p.Spot
		breakdown.EC2OnDemandCost += p.OnDemand
		breakdown.SpotSavings += p.Savings
		if job.Spot {
			breakdown.EC2SpotHours += p.Hours
		} else {
			breakdown.EC2OnDemandHours += p.Hours
		}
	}
	breakdown.JobsCompleted = len(jobs)
	breakdown.JobsMatched = total
	return nil
}

// spotInterruptionCount sums the SpotInterruptions metric across the Family
// dimension for the window. Zero data yields 0; a CloudWatch error degrades to 0
// (interruption counts are informational, not core to the cost figure).
func (r *Reporter) spotInterruptionCount(ctx context.Context, startTime, endTime time.Time) int {
	output, err := r.cwClient.GetMetricData(ctx, &cloudwatch.GetMetricDataInput{
		StartTime:         aws.Time(startTime),
		EndTime:           aws.Time(endTime),
		MetricDataQueries: spotInterruptionQueries(),
	})
	if err != nil {
		costLog.Warn(ctx, "spot interruption count unavailable", slog.String("error", err.Error()))
		return 0
	}

	var sum float64
	for _, result := range output.MetricDataResults {
		if result.Id == nil || *result.Id != spotInterruptionQueryID {
			continue
		}
		for _, v := range result.Values {
			sum += v
		}
	}
	return int(sum)
}

const spotInterruptionQueryID = "spot_interruptions"

// spotInterruptionQueries builds the metric-math query that sums the
// SpotInterruptions counter across the Family dimension (the real emissions
// carry a Family dimension, so a plain undimensioned lookup matches nothing).
func spotInterruptionQueries() []cwtypes.MetricDataQuery {
	return []cwtypes.MetricDataQuery{
		{
			Id:         aws.String(spotInterruptionQueryID),
			Expression: aws.String(`SUM(SEARCH('{RunsFleet,Family} MetricName="SpotInterruptions"', 'Sum', 3600))`),
			ReturnData: aws.Bool(true),
		},
	}
}

// generateMarkdownReport generates a markdown report from the cost breakdown.
func (r *Reporter) generateMarkdownReport(b *Breakdown) string {
	var buf bytes.Buffer

	buf.WriteString("# runs-fleet Daily Cost Report\n\n")
	buf.WriteString(fmt.Sprintf("**Date:** %s\n\n", b.Date))
	buf.WriteString(fmt.Sprintf("**24-Hour Total:** $%.2f\n\n", b.TotalCost))

	buf.WriteString("## EC2 Compute\n\n")
	buf.WriteString(fmt.Sprintf("- Spot instances: $%.2f (%.1f instance-hours)\n", b.EC2SpotCost, b.EC2SpotHours))
	buf.WriteString(fmt.Sprintf("- On-demand instances: $%.2f (%.1f instance-hours)\n", b.EC2OnDemandCost, b.EC2OnDemandHours))
	buf.WriteString(fmt.Sprintf("- **Spot savings:** $%.2f (%.0f%% discount)\n\n", b.SpotSavings, SpotDiscount*100))

	buf.WriteString("## Supporting Services\n\n")
	buf.WriteString(fmt.Sprintf("- Fargate orchestrator: $%.2f\n", b.FargateCost))
	buf.WriteString(fmt.Sprintf("- SQS: $%.2f\n", b.SQSCost))
	buf.WriteString(fmt.Sprintf("- DynamoDB: $%.2f\n", b.DynamoDBCost))
	buf.WriteString(fmt.Sprintf("- CloudWatch: $%.2f\n", b.CloudWatchCost))
	buf.WriteString(fmt.Sprintf("- S3: $%.2f\n\n", b.S3Cost))

	buf.WriteString("## Job Statistics\n\n")
	if b.JobsMatched > b.JobsCompleted {
		buf.WriteString(fmt.Sprintf("- Jobs completed: %d of %d (window truncated at the %d-job cap; EC2 costs undercount)\n",
			b.JobsCompleted, b.JobsMatched, jobWindowLimit))
	} else {
		buf.WriteString(fmt.Sprintf("- Jobs completed: %d\n", b.JobsCompleted))
	}
	buf.WriteString(fmt.Sprintf("- Spot interruptions: %d\n", b.SpotInterruptions))
	if b.JobsCompleted > 0 {
		costPerJob := b.TotalCost / float64(b.JobsCompleted)
		buf.WriteString(fmt.Sprintf("- Cost per job: $%.4f\n", costPerJob))
	}

	if b.RunnerMinuteCost > 0 {
		buf.WriteString("\n## Runner-Minute Cost (standard per-vCPU-minute pricing)\n\n")
		buf.WriteString(fmt.Sprintf("- Billable runner usage: %.0f vCPU-minutes\n", b.RunnerVcpuMinutes))
		buf.WriteString(fmt.Sprintf("- Standard runner-minute cost: $%.2f\n", b.RunnerMinuteCost))
		ec2Cost := b.EC2SpotCost + b.EC2OnDemandCost
		if ec2Cost > 0 {
			buf.WriteString(fmt.Sprintf("- runs-fleet EC2 compute: $%.2f (%.1fx lower)\n", ec2Cost, b.RunnerMinuteCost/ec2Cost))
		}
	}

	buf.WriteString("\n---\n")
	buf.WriteString("⚠️ **DISCLAIMER:** These costs are *estimates* based on hard-coded pricing data.\n")
	buf.WriteString("Actual AWS costs may vary. Use AWS Cost Explorer for accurate billing data.\n\n")
	buf.WriteString("*Report generated by runs-fleet*\n")

	return buf.String()
}
