version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - goconst
    - gocyclo
    - dupl
    - bodyclose
    - errorlint
    - revive
  settings:
    govet:
      enable:
        - shadow
    gocyclo:
      min-complexity: 30
    dupl:
      threshold: 150
    goconst:
      min-len: 2
      min-occurrences: 3
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
